// <auto-generated />
using System;
using EcomercerWebsite_Fruit.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcomercerWebsite_Fruit.Migrations
{
    [DbContext(typeof(EcomercerDataContext))]
    [Migration("20240605095631_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Bill", b =>
                {
                    b.Property<string>("BillID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DayBuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DayDelivery")
                        .HasColumnType("datetime2");

                    b.Property<double>("DeliveryFee")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatementInformationStatementID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WayDelivery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("StatementInformationStatementID");

                    b.ToTable("bills");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.BillInformation", b =>
                {
                    b.Property<string>("BillInformationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BillID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("BillInformationDiscount")
                        .HasColumnType("float");

                    b.Property<double>("ProductCost")
                        .HasColumnType("float");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BillInformationID");

                    b.HasIndex("BillID");

                    b.HasIndex("ProductID");

                    b.ToTable("billInformation");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Customer", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CustomerDoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CustomerGender")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CustomerIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerRole")
                        .HasColumnType("int");

                    b.Property<string>("RandomKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Favorite", b =>
                {
                    b.Property<string>("FavoriteID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FavoriteDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PickDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FavoriteID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.ToTable("favorites");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("ProductCost")
                        .HasColumnType("float");

                    b.Property<DateTime>("ProductDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductDiscount")
                        .HasColumnType("float");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductNumberAccess")
                        .HasColumnType("int");

                    b.Property<string>("ProductTypeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductTypeID");

                    b.HasIndex("ProviderID");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductID = "apple",
                            ProductCost = 65000.0,
                            ProductDate = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Apples are sweet or tart fruits with a crisp texture. They come in various colors, including red, green, and yellow. Apples are commonly eaten raw, cooked, or used in desserts like pies and crumbles.",
                            ProductDiscount = 0.0,
                            ProductImage = "apple.jpg",
                            ProductName = "Apple",
                            ProductNumberAccess = 30,
                            ProductTypeID = "2c1f5b4e-3a4e-4db4-85c3-89a7c3179e7d",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "pear",
                            ProductCost = 55000.0,
                            ProductDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Pears are sweet, juicy fruits with a smooth or slightly grainy texture. They come in various colors, including green, yellow, and red. Pears are eaten fresh, canned, or used in baking.",
                            ProductDiscount = 0.0,
                            ProductImage = "pear.jpg",
                            ProductName = "Pear",
                            ProductNumberAccess = 20,
                            ProductTypeID = "2c1f5b4e-3a4e-4db4-85c3-89a7c3179e7d",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "lemon",
                            ProductCost = 25000.0,
                            ProductDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Lemons are citrus fruits with a bright yellow skin and sour, juicy flesh. They are rich in vitamin C and are used for their juice, zest, and in cooking and baking.",
                            ProductDiscount = 0.0,
                            ProductImage = "lemon.jpg",
                            ProductName = "Lemon",
                            ProductNumberAccess = 35,
                            ProductTypeID = "2c1f5b4e-3a4e-4db4-85c3-89a7c3179e7d",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "orange",
                            ProductCost = 35000.0,
                            ProductDate = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Oranges are citrus fruits with a bright orange skin and juicy, sweet-tart flesh. They are rich in vitamin C and are commonly consumed fresh, juiced, or used in cooking.",
                            ProductDiscount = 0.0,
                            ProductImage = "orange.jpg",
                            ProductName = "Orange",
                            ProductNumberAccess = 20,
                            ProductTypeID = "2c1f5b4e-3a4e-4db4-85c3-89a7c3179e7d",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "mandarin",
                            ProductCost = 40000.0,
                            ProductDate = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "The mandarin (Citrus reticulata) is a small citrus tree fruit that belongs to the Rutaceae family. It is one of the original species of citrus and is known for its easy-to-peel skin, sweet flavor, and juicy segments. Mandarins are a popular fruit worldwide, enjoyed both fresh and in various culinary applications.",
                            ProductDiscount = 0.0,
                            ProductImage = "mandarin.jpg",
                            ProductName = "Mandarin",
                            ProductNumberAccess = 40000,
                            ProductTypeID = "2c1f5b4e-3a4e-4db4-85c3-89a7c3179e7d",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "peach",
                            ProductCost = 65000.0,
                            ProductDate = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Peaches are stone fruits with a fuzzy skin and juicy, sweet flesh. They come in yellow and white varieties and are eaten fresh, canned, or used in desserts.\r\n\r\n",
                            ProductDiscount = 0.0,
                            ProductImage = "peach.jpg",
                            ProductName = "Peach",
                            ProductNumberAccess = 25,
                            ProductTypeID = "1a90c514-3e9f-4a2b-8ab9-8e9a7357b30d",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "plum",
                            ProductCost = 65000.0,
                            ProductDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Plums are stone fruits with a smooth skin and juicy, sweet-tart flesh. They come in various colors, including purple, red, and yellow. Plums are eaten fresh, dried into prunes, or used in cooking.",
                            ProductDiscount = 0.0,
                            ProductImage = "plum.jpg",
                            ProductName = "Plum",
                            ProductNumberAccess = 35,
                            ProductTypeID = "1a90c514-3e9f-4a2b-8ab9-8e9a7357b30d",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "apricot",
                            ProductCost = 40000.0,
                            ProductDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Apricots (Prunus armeniaca) are small, round stone fruits with a velvety skin and sweet-tart flavor. They are typically yellow to orange in color, often with a reddish blush.",
                            ProductDiscount = 0.0,
                            ProductImage = "apricot.jpg",
                            ProductName = "Apricot",
                            ProductNumberAccess = 40,
                            ProductTypeID = "1a90c514-3e9f-4a2b-8ab9-8e9a7357b30d",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "cherry",
                            ProductCost = 250000.0,
                            ProductDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Cherries are small, round stone fruits known for their vibrant color and sweet or tart flavor. They come in two main types: sweet cherries (Prunus avium) and sour cherries (Prunus cerasus).",
                            ProductDiscount = 0.0,
                            ProductImage = "cherry.jpg",
                            ProductName = "Cherry",
                            ProductNumberAccess = 10,
                            ProductTypeID = "1a90c514-3e9f-4a2b-8ab9-8e9a7357b30d",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "strawberry",
                            ProductCost = 125000.0,
                            ProductDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Strawberries are juicy, red berries that are widely appreciated for their sweet flavor and aromatic fragrance. They are among the most popular and versatile fruits globally.",
                            ProductDiscount = 0.0,
                            ProductImage = "strawberry.jpg",
                            ProductName = "Strawberry",
                            ProductNumberAccess = 25,
                            ProductTypeID = "e18b417d-fc87-4e0d-9c50-74a8b9c9b77f",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "blueberry",
                            ProductCost = 225000.0,
                            ProductDate = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Blueberries are small, round berries with a deep blue to purple-black hue. They are celebrated for their sweet flavor, antioxidant-rich profile, and versatility in culinary applications.",
                            ProductDiscount = 0.0,
                            ProductImage = "blueberry.jpg",
                            ProductName = "Blueberry",
                            ProductNumberAccess = 20,
                            ProductTypeID = "e18b417d-fc87-4e0d-9c50-74a8b9c9b77f",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "grape",
                            ProductCost = 125000.0,
                            ProductDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Grapes are small, spherical fruits known for their sweet and juicy taste, often eaten fresh or processed into various products like wine, juice, and raisins. They grow in clusters on vines belonging to the Vitis genus.",
                            ProductDiscount = 0.0,
                            ProductImage = "grape.jpg",
                            ProductName = "Grape",
                            ProductNumberAccess = 25,
                            ProductTypeID = "e18b417d-fc87-4e0d-9c50-74a8b9c9b77f",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "kiwi",
                            ProductCost = 250000.0,
                            ProductDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "The kiwi, also known as the kiwifruit, is a small, oval-shaped fruit with fuzzy brown skin and vibrant green flesh dotted with tiny edible black seeds. It is renowned for its unique flavor, nutritional richness, and distinctive appearance.",
                            ProductDiscount = 0.0,
                            ProductImage = "kiwi.jpg",
                            ProductName = "Kiwi",
                            ProductNumberAccess = 25,
                            ProductTypeID = "e18b417d-fc87-4e0d-9c50-74a8b9c9b77f",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "coconut",
                            ProductCost = 25000.0,
                            ProductDate = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "The coconut is a versatile tropical fruit known for its large size, fibrous husk, and unique nutritional properties. It is prized for its sweet, refreshing water and creamy flesh, which are used in various culinary, medicinal, and industrial applications.",
                            ProductDiscount = 0.10000000000000001,
                            ProductImage = "coconut.jpg",
                            ProductName = "Coconut",
                            ProductNumberAccess = 30,
                            ProductTypeID = "2f72c7e1-5a4e-4b79-a8a7-b9e4cf2d9a8c",
                            ProductUnit = "fruit",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "walnut",
                            ProductCost = 335000.0,
                            ProductDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Walnuts are nutritious nuts known for their distinctively earthy flavor and crunchy texture. They are highly versatile and widely used in various culinary applications, from savory dishes to baked goods and desserts.",
                            ProductDiscount = 0.10000000000000001,
                            ProductImage = "walnut.jpg",
                            ProductName = "Walnut",
                            ProductNumberAccess = 20,
                            ProductTypeID = "2f72c7e1-5a4e-4b79-a8a7-b9e4cf2d9a8c",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "almond",
                            ProductCost = 225000.0,
                            ProductDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Almonds are highly versatile nuts celebrated for their delicate flavor, crunchy texture, and numerous health benefits. They are one of the most widely cultivated tree nuts globally and are utilized in various culinary, medicinal, and cosmetic applications.",
                            ProductDiscount = 0.0,
                            ProductImage = "almond.jpg",
                            ProductName = "Almond",
                            ProductNumberAccess = 10,
                            ProductTypeID = "2f72c7e1-5a4e-4b79-a8a7-b9e4cf2d9a8c",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "mango",
                            ProductCost = 35000.0,
                            ProductDate = new DateTime(2024, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Mangoes are tropical fruits with a sweet, juicy, and fibrous flesh. They have a large pit and a tough skin that ranges from green to red or orange when ripe. Mangoes are eaten fresh, used in desserts, or made into smoothies.",
                            ProductDiscount = 0.0,
                            ProductImage = "mango.jpg",
                            ProductName = "Mango",
                            ProductNumberAccess = 20,
                            ProductTypeID = "b1a3e54f-c18f-47c1-87d1-4a2d8f9b77bc",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "pineapple",
                            ProductCost = 35000.0,
                            ProductDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Pineapples are tropical fruits with a tough, spiky exterior and sweet, tangy flesh. They are commonly eaten fresh, canned, or used in cooking and baking.",
                            ProductDiscount = 0.0,
                            ProductImage = "pineapple.jpg",
                            ProductName = "Pineapple",
                            ProductNumberAccess = 30,
                            ProductTypeID = "b1a3e54f-c18f-47c1-87d1-4a2d8f9b77bc",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "banana",
                            ProductCost = 45000.0,
                            ProductDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Bananas are long, yellow fruits with a soft, sweet flesh. They are high in potassium and are commonly eaten raw, used in baking, or added to smoothies.",
                            ProductDiscount = 0.0,
                            ProductImage = "banana.jpg",
                            ProductName = "Banana",
                            ProductNumberAccess = 10,
                            ProductTypeID = "b1a3e54f-c18f-47c1-87d1-4a2d8f9b77bc",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "papaya",
                            ProductCost = 35000.0,
                            ProductDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Papayas are tropical fruits with a green or yellow skin and sweet, orange flesh. They contain black seeds and are eaten fresh, used in salads, or made into smoothies and juices.",
                            ProductDiscount = 0.0,
                            ProductImage = "papaya.jpg",
                            ProductName = "Papaya",
                            ProductNumberAccess = 10,
                            ProductTypeID = "b1a3e54f-c18f-47c1-87d1-4a2d8f9b77bc",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "durian",
                            ProductCost = 185000.0,
                            ProductDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Durian is a tropical fruit renowned for its distinctive aroma, large size, and custard-like flesh. Often referred to as the \"king of fruits,\" durian holds a special place in Southeast Asian cuisine and culture, despite its divisive smell.",
                            ProductDiscount = 0.0,
                            ProductImage = "durian.jpg",
                            ProductName = "durian",
                            ProductNumberAccess = 30,
                            ProductTypeID = "b1a3e54f-c18f-47c1-87d1-4a2d8f9b77bc",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "watermelon",
                            ProductCost = 15000.0,
                            ProductDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Watermelons are large, juicy fruits with a green rind and sweet, red or pink flesh. They are a popular summer fruit, eaten fresh or used in salads and beverages.\r\n\r\n",
                            ProductDiscount = 0.0,
                            ProductImage = "watermelon.jpg",
                            ProductName = "Watermelon",
                            ProductNumberAccess = 35,
                            ProductTypeID = "b1a3e54f-c18f-47c1-87d1-4a2d8f9b77bc",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "cantaloupe",
                            ProductCost = 35000.0,
                            ProductDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Cantaloupe, also known as muskmelon, is a sweet and refreshing melon with a vibrant orange flesh and a distinctively aromatic flavor. It is widely loved for its juicy texture and subtle sweetness, making it a popular choice for snacks, desserts, and fruit salads during the summer months.",
                            ProductDiscount = 0.0,
                            ProductImage = "cantaloupe.jpg",
                            ProductName = "Cantaloupe",
                            ProductNumberAccess = 20,
                            ProductTypeID = "6c3b90d1-4e9f-4b7a-8b9e-1f4a2d8c9b7f",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        },
                        new
                        {
                            ProductID = "pomegranate",
                            ProductCost = 60000.0,
                            ProductDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductDescription = "Pomegranates are round fruits with a tough, reddish skin and a plethora of juicy, red seeds inside. They have a sweet-tart flavor and are eaten fresh or used in juices and cooking.",
                            ProductDiscount = 0.0,
                            ProductImage = "pomegranate.jpg",
                            ProductName = "Pomegranate",
                            ProductNumberAccess = 30,
                            ProductTypeID = "6c3b90d1-4e9f-4b7a-8b9e-1f4a2d8c9b7f",
                            ProductUnit = "kilogram",
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52"
                        });
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.ProductType", b =>
                {
                    b.Property<string>("ProductTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductTypeID");

                    b.ToTable("productTypes");

                    b.HasData(
                        new
                        {
                            ProductTypeID = "2c1f5b4e-3a4e-4db4-85c3-89a7c3179e7d",
                            ProductTypeDescription = "Contain one or more seeds inside",
                            ProductTypeName = "Seeded Fruits"
                        },
                        new
                        {
                            ProductTypeID = "1a90c514-3e9f-4a2b-8ab9-8e9a7357b30d",
                            ProductTypeDescription = "Have a hard pit inside, surrounded by soft flesh.",
                            ProductTypeName = "Stone Fruits"
                        },
                        new
                        {
                            ProductTypeID = "e18b417d-fc87-4e0d-9c50-74a8b9c9b77f",
                            ProductTypeDescription = "Have many small seeds distributed throughout the flesh.",
                            ProductTypeName = "Berries"
                        },
                        new
                        {
                            ProductTypeID = "2f72c7e1-5a4e-4b79-a8a7-b9e4cf2d9a8c",
                            ProductTypeDescription = "Have a hard shell protecting the inner flesh.",
                            ProductTypeName = "Hard-Shell Fruits"
                        },
                        new
                        {
                            ProductTypeID = "b1a3e54f-c18f-47c1-87d1-4a2d8f9b77bc",
                            ProductTypeDescription = "Typically grow in tropical regions.",
                            ProductTypeName = "Tropical Fruits"
                        },
                        new
                        {
                            ProductTypeID = "6c3b90d1-4e9f-4b7a-8b9e-1f4a2d8c9b7f",
                            ProductTypeDescription = "Grow in temperate regions.",
                            ProductTypeName = "Temperate Fruits"
                        },
                        new
                        {
                            ProductTypeID = "4a1b7c3d-8e9f-4c2d-8a9b-1f7c3b9e4d5a",
                            ProductTypeDescription = "Grow in subtropical regions.",
                            ProductTypeName = "Subtropical Fruits"
                        });
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Provider", b =>
                {
                    b.Property<string>("ProviderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProviderID");

                    b.ToTable("providers");

                    b.HasData(
                        new
                        {
                            ProviderID = "9a0f35a4-f431-4a0d-8427-fbf9b60a8e52",
                            Email = "fresh.fruit.inc@gmail.com",
                            Logo = "logo.png",
                            ProviderAddress = "23 Hoàng Văn Thái, Thanh Xuân, Hà Nội",
                            ProviderContact = "Nguyễn Hoàng Hà",
                            ProviderDescription = "Fresh Fruit Inc. is integral to bringing fresh, nutritious fruits from farms to consumers around the world. They encompass a wide range of activities, from cultivation and quality control to distribution and marketing, all while striving for sustainability and innovation.",
                            ProviderName = "Fresh Fruit Inc.",
                            ProviderPhone = "0334564456"
                        });
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.StatementInformation", b =>
                {
                    b.Property<string>("StatementID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatementID");

                    b.ToTable("statementInformations");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Bill", b =>
                {
                    b.HasOne("EcomercerWebsite_Fruit.Models.Customer", "CustomerNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("CustomerID");

                    b.HasOne("EcomercerWebsite_Fruit.Models.StatementInformation", null)
                        .WithMany("Bills")
                        .HasForeignKey("StatementInformationStatementID");

                    b.Navigation("CustomerNavigation");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.BillInformation", b =>
                {
                    b.HasOne("EcomercerWebsite_Fruit.Models.Bill", "BillNavigation")
                        .WithMany("BillInformations")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcomercerWebsite_Fruit.Models.Product", "ProductNavigation")
                        .WithMany("BillInformations")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillNavigation");

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Favorite", b =>
                {
                    b.HasOne("EcomercerWebsite_Fruit.Models.Customer", "CustomerNavigation")
                        .WithMany("Favorites")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcomercerWebsite_Fruit.Models.Product", "ProductNavigation")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerNavigation");

                    b.Navigation("ProductNavigation");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Product", b =>
                {
                    b.HasOne("EcomercerWebsite_Fruit.Models.ProductType", "ProductTypeNavigation")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcomercerWebsite_Fruit.Models.Provider", "ProviderNavigation")
                        .WithMany("Products")
                        .HasForeignKey("ProviderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductTypeNavigation");

                    b.Navigation("ProviderNavigation");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Bill", b =>
                {
                    b.Navigation("BillInformations");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Customer", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Product", b =>
                {
                    b.Navigation("BillInformations");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.Provider", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcomercerWebsite_Fruit.Models.StatementInformation", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
